# Generated by Django 4.0.2 on 2022-03-01 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_alter_classcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('default_county', models.CharField(blank=True, max_length=80, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('active_class_package', models.BooleanField(default=False)),
                ('class_package_type', models.CharField(blank=True, max_length=30, null=True)),
                ('class_tokens', models.IntegerField(blank=True, null=True)),
                ('package_expiry', models.DateField(blank=True, null=True)),
                ('classes_attended', models.ManyToManyField(blank=True, to='classes.SingleExerciseClass')),
                ('fav_class_categories', models.ManyToManyField(blank=True, to='classes.ClassCategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
