# Generated by Django 4.0.2 on 2022-03-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='package_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
