# Generated by Django 4.0.2 on 2022-03-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_options_userprofile_package_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='classes_attended',
            new_name='classes',
        ),
    ]
