# Generated by Django 4.0.2 on 2022-03-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0002_alter_instructor_description"),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleexerciseclass",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="instructors.instructor",
            ),
        ),
    ]
