# Generated by Django 4.0.2 on 2022-02-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleexerciseclass',
            name='ability_level',
            field=models.CharField(blank=True, choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='singleexerciseclass',
            name='participants',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
