# Generated by Django 4.0.2 on 2022-02-18 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_singleexerciseclass_ability_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleexerciseclass',
            name='max_capacity',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(150)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singleexerciseclass',
            name='token_cost',
            field=models.PositiveSmallIntegerField(default='15', validators=[django.core.validators.MaxValueValidator(30)]),
            preserve_default=False,
        ),
    ]
