# Generated by Django 4.0.2 on 2022-02-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_singleexerciseclass_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcategory',
            options={'verbose_name_plural': 'Class Categories'},
        ),
        migrations.AlterModelOptions(
            name='singleexerciseclass',
            options={'verbose_name_plural': 'Single Exercise Classes'},
        ),
    ]
