# Generated by Django 4.0.2 on 2022-03-14 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classcategory_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleexerciseclass',
            name='category',
            field=models.ForeignKey(default="2", on_delete=django.db.models.deletion.CASCADE, to='classes.classcategory'),
            preserve_default=False,
        ),
    ]
