# Generated by Django 4.0.2 on 2022-03-04 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_alter_classcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleexerciseclass',
            name='participants',
        ),
        migrations.AddField(
            model_name='singleexerciseclass',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
