# Generated by Django 4.0.2 on 2022-03-05 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_singleexerciseclass_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleexerciseclass',
            old_name='date',
            new_name='class_date',
        ),
        migrations.AlterField(
            model_name='classcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='singleexerciseclass',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
