# Generated by Django 4.0.2 on 2022-03-09 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_from', models.CharField(max_length=100)),
                ('reply_email', models.EmailField(max_length=254)),
                ('message_subject', models.CharField(max_length=200)),
                ('message_text', models.TextField()),
                ('message_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
