# Generated by Django 4.0.2 on 2022-03-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply_email',
            field=models.EmailField(default='default_email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message_from',
            field=models.CharField(max_length=100),
        ),
    ]
