# Generated by Django 4.0.2 on 2022-02-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_classaccesspackage_amount_of_tokens_and_more'),
        ('classes', '0004_alter_classcategory_options_and_more'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='access_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.classaccesspackage'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='exercise_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.singleexerciseclass'),
        ),
    ]
