# Generated by Django 4.0.2 on 2022-03-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_classcategory_id_alter_singleexerciseclass_id'),
        ('reviews', '0002_alter_classcategoryreview_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcategoryreview',
            options={'verbose_name': 'Class Category Review', 'verbose_name_plural': 'Class Category Reviews'},
        ),
        migrations.RenameField(
            model_name='classcategoryreview',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='classcategoryreview',
            name='review_subject_id',
        ),
        migrations.AddField(
            model_name='classcategoryreview',
            name='review_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.classcategory'),
            preserve_default=False,
        ),
    ]
