# Generated by Django 4.0.2 on 2022-03-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classaccesspackage',
            name='friendly_name',
            field=models.CharField(default='default name', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classaccesspackage',
            name='type',
            field=models.CharField(choices=[('UU', 'Unlimited Use'), ('TK', 'Token Package')], default='TK', max_length=30),
            preserve_default=False,
        ),
    ]
