# Generated by Django 4.0.2 on 2022-03-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_classaccesspackage_amount_of_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classaccesspackage',
            name='unlimited_tokens',
        ),
    ]
